### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by bennergarrett** [jordens/pyflycapture2#30]
I'm using this on Ubuntu 14.04 so maybe that is the issue but if not I'm getting an import error after I install and try to run one of the examples.

"/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "AsyncTriggerEx.py", line 18, in <module>
    import PyCapture2
  File "build/bdist.linux-x86_64/egg/PyCapture2.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/PyCapture2.py", line 6, in __bootstrap__
ImportError: /home/user/.python-eggs/PyCapture2-0.0.0-py2.7-linux-x86_64.egg-tmp/PyCapture2.so: undefined symbol: fc2ImageStatisticsDisableAll"

The .so file is there yet it acts as if there is something undefined inside the library.  I have flycapture2 installed for the 14.04 version x64.  That has been tested and works with the Chameleon 3 camera

**Comment by jordens** [comment]
Probably the version of flycapture2 has evolved and diverged from the `*.pxd` files. This is like #21 or #24 .
You'll probably have to regenerated those files using `cwarp`.

**Comment by jordens** [comment]
Does it work now? Anything that can be done here?
