### ISSUE TITLE
flycapture2.ApiError: Bus Master Failure

### ISSUE THREAD

**Issue by arshv27** [jordens/pyflycapture2#31]
Hi
I am getting the following error:

```
{'major': 2, 'type': 3, 'build': 31, 'minor': 13}
0
Traceback (most recent call last):
  File "test_flycapture2.py", line 47, in <module>
    test()
  File "test_flycapture2.py", line 27, in test
    c.connect(*c.get_camera_from_index(0))
  File "src/flycapture2.pyx", line 116, in flycapture2.Context.get_camera_from_index (src/flycapture2.c:3299)
    raise_error(r)
  File "src/flycapture2.pyx", line 65, in flycapture2.raise_error (src/flycapture2.c:2460)
    raise ApiError(e, fc2ErrorToDescription(e))
flycapture2.ApiError: (19, 'Bus Master Failure.')
```

@jordens I saw you give an output with a similar error on one of the issues pertaining to another problem. Can you guide me to the likely cause/solution?
I believe it's an issue with the system detecting the camera, but I'm not very sure. Please help, I'm not very familiar with this!

**Comment by jordens** [comment]
~~IIRC in #16 it was a compilation issue. Could be the case here as well.~~
No. In #16 there was no camera connected. I just ran that code to test the method existence.

But I don't have access to these systems anymore and don't use flycapture/pyflucapture anymore. Maybe someone else has an idea.

**Comment by jordens** [comment]
Does it work now? Anything that can be done?

**Comment by clarencesees** [comment]
Hi, I have a similar issue but this happened after connecting to the camera.
In test2_flycapture2.py, I receive the error (19, b'Bus Master Failure.') from attempting to set_video_mode_and_frame_rate and get_video_mode_and_frame_rate. Any ideas?
